// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6K3_m3fqMvILOlO-od2ooWUrZ3gQgQQ',
    appId: '1:480522145713:web:9018f958c1d2cb29fb7790',
    messagingSenderId: '480522145713',
    projectId: 'petrolcounter-34bab',
    authDomain: 'petrolcounter-34bab.firebaseapp.com',
    databaseURL: 'https://petrolcounter-34bab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petrolcounter-34bab.appspot.com',
    measurementId: 'G-P8CBRCM2WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKHRBw0rDVK8ybbpHjeyNBbkqXcDfrxu0',
    appId: '1:480522145713:android:03558ef588a848dcfb7790',
    messagingSenderId: '480522145713',
    projectId: 'petrolcounter-34bab',
    databaseURL: 'https://petrolcounter-34bab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petrolcounter-34bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUktSmwiyZQm0HkgKH9CM6YUsl750AXR0',
    appId: '1:480522145713:ios:8026bebcd86a2e6ffb7790',
    messagingSenderId: '480522145713',
    projectId: 'petrolcounter-34bab',
    databaseURL: 'https://petrolcounter-34bab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petrolcounter-34bab.appspot.com',
    iosBundleId: 'com.example.petrolchik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUktSmwiyZQm0HkgKH9CM6YUsl750AXR0',
    appId: '1:480522145713:ios:8026bebcd86a2e6ffb7790',
    messagingSenderId: '480522145713',
    projectId: 'petrolcounter-34bab',
    databaseURL: 'https://petrolcounter-34bab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petrolcounter-34bab.appspot.com',
    iosBundleId: 'com.example.petrolchik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe6K3_m3fqMvILOlO-od2ooWUrZ3gQgQQ',
    appId: '1:480522145713:web:412e2b739d10900efb7790',
    messagingSenderId: '480522145713',
    projectId: 'petrolcounter-34bab',
    authDomain: 'petrolcounter-34bab.firebaseapp.com',
    databaseURL: 'https://petrolcounter-34bab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'petrolcounter-34bab.appspot.com',
    measurementId: 'G-N9K1T1SJ95',
  );
}
