name: petrolchik
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  #mapping and location
  yandex_maps_mapkit: 4.7.2-beta6
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1

  #firebase repos
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_analytics: ^11.2.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  firebase_database: ^11.0.4

  #UI/UX
  pretty_animated_buttons: ^0.0.2
  rive: ^0.13.12
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8

  #state managers 
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #API's
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  #retrofit dep
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  assets:
  - .env.prod
  - assets/Lottie/Animation_auth.json
  - assets/image_asset/pngwing.png

